
spring.security.user.name=siva
spring.security.user.password=naga
server.port=1111
spring.application.name=Collecting-Data

spring.datasource.url= jdbc:mysql://localhost:3306/details
spring.datasource.driverClassName=  com.mysql.cj.jdbc.Driver
spring.datasource.username= root
spring.datasource.password= root

spring.jpa.show-sql=true
spring.jpa.generate-ddl=true

spring.jpa.hibernate.ddl-auto=update 

